server:
  port: 8082

spring:
  cloud:
    gateway:
      routes:
        - id: sensor-telemetry-service
          uri: lb://SENSOR-TELEMETRY-SERVICE
          predicates:
            - Path=/api/sensors/**
          filters:
            - name: AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/